import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import Layout from '@/components/layout/Layout';
import SEO from '@/components/SEO';
import Breadcrumbs from '@/components/Breadcrumbs';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { 
  Calendar,
  Clock,
  User,
  ArrowLeft,
  Phone,
  Share2,
  Tag,
  Loader2,
  BookOpen,
  CheckCircle,
  MessageCircle,
  Facebook,
  Twitter,
  Linkedin,
  AlertCircle,
  Lightbulb,
  ChevronRight
} from 'lucide-react';
import { seoBlogPosts } from '@/data/seoBlogPosts';
import { autoGeneratedBlogs } from '@/data/autoGeneratedBlogs';
import newBlogPosts from '@/data/newBlogPosts';
import staticBlogPosts from '@/data/blogPosts';

// Combine all blog sources
const allBlogPosts = [...autoGeneratedBlogs, ...seoBlogPosts, ...newBlogPosts, ...staticBlogPosts];

const API_URL = process.env.REACT_APP_BACKEND_URL || '';

// Transform CMS blog data to match static data format
const transformCmsBlog = (cmsData) => {
  if (!cmsData || !cmsData.content) return null;
  const content = cmsData.content;
  
  return {
    id: cmsData.slug,
    slug: cmsData.slug,
    title: cmsData.title,
    metaTitle: cmsData.meta_title,
    metaDescription: cmsData.meta_description,
    keywords: cmsData.keywords?.join(', '),
    author: content.author || 'Dr. B Harsha Vardhana Reddy',
    publishedDate: cmsData.published_at || cmsData.created_at,
    category: content.category || 'Orthopedics',
    readTime: content.readTime || '5 min',
    imageUrl: content.imageUrl,
    excerpt: content.excerpt,
    content: content.body || content.content,
    tags: cmsData.keywords || [],
    keyTakeaways: content.keyTakeaways || [],
    tableOfContents: content.tableOfContents || []
  };
};

// Parse markdown content into structured sections
const parseContent = (content) => {
  if (!content) return [];
  
  const lines = content.split('\n');
  const sections = [];
  let currentSection = null;
  let currentContent = [];
  
  lines.forEach((line) => {
    const h2Match = line.match(/^## (.+)/);
    const h3Match = line.match(/^### (.+)/);
    const h4Match = line.match(/^#### (.+)/);
    
    if (h2Match) {
      if (currentSection) {
        currentSection.content = currentContent.join('\n');
        sections.push(currentSection);
      }
      currentSection = { type: 'h2', title: h2Match[1], content: '' };
      currentContent = [];
    } else if (h3Match) {
      if (currentSection) {
        currentSection.content = currentContent.join('\n');
        sections.push(currentSection);
      }
      currentSection = { type: 'h3', title: h3Match[1], content: '' };
      currentContent = [];
    } else if (h4Match) {
      if (currentSection) {
        currentSection.content = currentContent.join('\n');
        sections.push(currentSection);
      }
      currentSection = { type: 'h4', title: h4Match[1], content: '' };
      currentContent = [];
    } else {
      currentContent.push(line);
    }
  });
  
  if (currentSection) {
    currentSection.content = currentContent.join('\n');
    sections.push(currentSection);
  } else if (currentContent.length > 0) {
    sections.push({ type: 'intro', title: '', content: currentContent.join('\n') });
  }
  
  return sections;
};

// Render content with proper formatting
const ContentSection = ({ section, index }) => {
  const formatText = (text) => {
    if (!text) return null;
    
    // Process the text
    let processed = text
      .replace(/\*\*(.*?)\*\*/g, '<strong class="text-foreground font-semibold">$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>');
    
    // Split by paragraphs and list items
    const parts = processed.split('\n').filter(p => p.trim());
    
    return parts.map((part, i) => {
      const trimmed = part.trim();
      
      // List item
      if (trimmed.startsWith('- ') || trimmed.startsWith('• ')) {
        return (
          <li key={i} className="flex items-start gap-3 py-1">
            <ChevronRight className="w-4 h-4 text-primary mt-1 flex-shrink-0" />
            <span dangerouslySetInnerHTML={{ __html: trimmed.substring(2) }} />
          </li>
        );
      }
      
      // Numbered list
      const numberedMatch = trimmed.match(/^(\d+)\.\s*(.+)/);
      if (numberedMatch) {
        return (
          <li key={i} className="flex items-start gap-3 py-1">
            <span className="w-6 h-6 bg-primary/10 text-primary rounded-full flex items-center justify-center flex-shrink-0 text-sm font-medium">
              {numberedMatch[1]}
            </span>
            <span dangerouslySetInnerHTML={{ __html: numberedMatch[2] }} />
          </li>
        );
      }
      
      // Regular paragraph
      if (trimmed) {
        return (
          <p key={i} className="text-muted-foreground leading-relaxed mb-4" dangerouslySetInnerHTML={{ __html: trimmed }} />
        );
      }
      
      return null;
    });
  };

  const hasListItems = section.content && (section.content.includes('\n- ') || section.content.includes('\n• ') || /\n\d+\.\s/.test(section.content));

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ delay: index * 0.05 }}
      className="mb-8"
    >
      {section.type === 'h2' && (
        <h2 className="text-2xl font-serif font-semibold text-foreground mb-4 pb-3 border-b border-border flex items-center gap-3">
          <span className="w-1 h-8 bg-primary rounded-full" />
          {section.title}
        </h2>
      )}
      {section.type === 'h3' && (
        <h3 className="text-xl font-serif font-semibold text-foreground mb-3 mt-6 flex items-center gap-2">
          <Lightbulb className="w-5 h-5 text-accent" />
          {section.title}
        </h3>
      )}
      {section.type === 'h4' && (
        <h4 className="text-lg font-semibold text-foreground mb-2 mt-4">
          {section.title}
        </h4>
      )}
      
      {hasListItems ? (
        <ul className="space-y-2 my-4">
          {formatText(section.content)}
        </ul>
      ) : (
        <div>{formatText(section.content)}</div>
      )}
    </motion.div>
  );
};

const BlogPost = () => {
  const { slug } = useParams();
  const [post, setPost] = useState(null);
  const [loading, setLoading] = useState(true);
  const [relatedPosts, setRelatedPosts] = useState([]);
  const [activeSection, setActiveSection] = useState(0);

  useEffect(() => {
    const fetchBlog = async () => {
      setLoading(true);
      let foundPost = null;
      
      // Try fetching from blog_posts collection first (AI-generated posts)
      try {
        const response = await fetch(`${API_URL}/api/blog/${slug}`);
        if (response.ok) {
          const blogData = await response.json();
          // Blog posts from API have direct fields, not nested in content
          foundPost = {
            id: blogData.id || blogData.slug,
            slug: blogData.slug,
            title: blogData.title,
            content: blogData.content,
            excerpt: blogData.excerpt,
            author: blogData.author || 'Dr. B Harsha Vardhana Reddy',
            publishedDate: blogData.published_date,
            imageUrl: blogData.image_url,
            tags: blogData.tags || [],
            readTime: '5 min read',
            category: blogData.tags?.[0] || 'Orthopedics'
          };
        }
      } catch (err) {
        console.warn('API fetch failed, trying static data:', err.message);
      }
      
      // Fallback to static blog data
      if (!foundPost) {
        foundPost = allBlogPosts.find(p => p.slug === slug);
      }
      
      setPost(foundPost);
      
      if (foundPost) {
        const postTags = foundPost.tags || [];
        const related = allBlogPosts
          .filter(p => p.slug !== slug)
          .filter(p => (p.tags || []).some(tag => postTags.includes(tag)))
          .slice(0, 3);
        setRelatedPosts(related);
      }
      
      setLoading(false);
    };

    fetchBlog();
    window.scrollTo(0, 0);
  }, [slug]);

  const handleShare = (platform) => {
    const url = window.location.href;
    const title = post?.title || '';
    
    const shareUrls = {
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,
      twitter: `https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(title)}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`,
      whatsapp: `https://wa.me/?text=${encodeURIComponent(title + ' ' + url)}`
    };
    
    window.open(shareUrls[platform], '_blank', 'width=600,height=400');
  };

  const formatDate = (dateString) => {
    if (!dateString || dateString === 'Invalid Date') return 'Recently Published';
    try {
      const date = new Date(dateString);
      if (isNaN(date.getTime())) return 'Recently Published';
      return date.toLocaleDateString('en-IN', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
    } catch {
      return 'Recently Published';
    }
  };

  const getPostDate = (postData) => {
    return postData?.publishedDate || postData?.published_date || postData?.date || null;
  };

  if (loading) {
    return (
      <Layout>
        <div className="min-h-screen flex items-center justify-center">
          <Loader2 className="w-10 h-10 animate-spin text-primary" />
          <span className="ml-4 text-lg text-muted-foreground">Loading article...</span>
        </div>
      </Layout>
    );
  }
  
  if (!post) {
    return (
      <Layout>
        <div className="min-h-screen flex flex-col items-center justify-center py-20">
          <BookOpen className="w-20 h-20 text-muted-foreground/30 mb-6" />
          <h1 className="text-2xl font-bold mb-4">Article Not Found</h1>
          <p className="text-muted-foreground mb-6">The article you&apos;re looking for doesn&apos;t exist or has been moved.</p>
          <Link to="/blog">
            <Button className="gap-2">
              <ArrowLeft className="w-4 h-4" />
              Back to Blog
            </Button>
          </Link>
        </div>
      </Layout>
    );
  }

  // Parse content into sections
  const contentSections = parseContent(post.content);
  
  // Generate table of contents from sections
  const tableOfContents = contentSections
    .filter(s => s.type === 'h2' || s.type === 'h3')
    .map((s, i) => ({ title: s.title, type: s.type, index: i }));

  // Generate key takeaways
  const keyTakeaways = post.keyTakeaways?.length > 0 ? post.keyTakeaways : [
    `Comprehensive guide to ${post.title?.toLowerCase().replace('2025', '').trim()}`,
    'Evidence-based treatment approaches',
    'Recovery timelines and expectations',
    'Cost information for Hyderabad',
    'Expert recommendations from Dr. Harsha'
  ];

  // Article Schema for SEO
  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "MedicalWebPage",
    "headline": post.title,
    "author": {
      "@type": "Person",
      "name": post.author || "Dr. B Harsha Vardhana Reddy",
      "jobTitle": "Senior Consultant Orthopedic Surgeon"
    },
    "datePublished": getPostDate(post),
    "image": post.imageUrl,
    "publisher": {
      "@type": "Organization",
      "name": "Dr. B Harsha Vardhana Reddy"
    }
  };

  return (
    <Layout>
      <SEO 
        title={post.metaTitle || `${post.title} | Dr. Harsha Reddy`}
        description={post.metaDescription || post.excerpt}
        keywords={post.keywords}
      />
      
      <script type="application/ld+json">
        {JSON.stringify(articleSchema)}
      </script>

      {/* Breadcrumb */}
      <div className="bg-secondary border-b border-border">
        <div className="container-medical py-3">
          <Breadcrumbs 
            items={[
              { name: 'Blog', path: '/blog' },
              { name: post.title, path: `/blog/${slug}` }
            ]}
          />
        </div>
      </div>

      {/* Hero Section - Compact */}
      <section className="bg-gradient-to-br from-charcoal via-charcoal/95 to-charcoal py-12 md:py-16">
        <div className="container-medical">
          <div className="max-w-4xl">
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="flex flex-wrap gap-3 mb-4"
            >
              <span className="inline-flex items-center gap-1 px-3 py-1 bg-primary text-white text-sm font-medium rounded-full">
                <Tag className="w-3 h-3" />
                {post.category || post.tags?.[0] || 'Orthopedics'}
              </span>
              <span className="inline-flex items-center gap-1 px-3 py-1 bg-white/10 text-white/80 text-sm rounded-full">
                <Clock className="w-3 h-3" />
                {post.readTime || '5 min read'}
              </span>
            </motion.div>
            
            <motion.h1 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-2xl md:text-3xl lg:text-4xl font-serif font-semibold text-white mb-4"
            >
              {post.title}
            </motion.h1>
            
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="flex flex-wrap items-center gap-4 text-white/70 text-sm"
            >
              <div className="flex items-center gap-2">
                <User className="w-4 h-4" />
                {post.author || 'Dr. B Harsha Vardhana Reddy'}
              </div>
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4" />
                {formatDate(getPostDate(post))}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <article className="section-padding bg-gradient-to-b from-background to-secondary/20">
        <div className="container-medical">
          <div className="grid lg:grid-cols-12 gap-8">
            {/* Content Column */}
            <div className="lg:col-span-8">
              {/* Key Takeaways Card */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-gradient-to-br from-primary/5 via-accent/5 to-primary/5 rounded-2xl p-6 mb-8 border border-primary/20 shadow-sm"
              >
                <h2 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-primary" />
                  Key Takeaways
                </h2>
                <ul className="grid sm:grid-cols-2 gap-3">
                  {keyTakeaways.slice(0, 5).map((point, idx) => (
                    <li key={idx} className="flex items-start gap-2 text-sm text-muted-foreground bg-white/50 rounded-lg p-3">
                      <span className="w-5 h-5 bg-primary text-white rounded-full flex items-center justify-center flex-shrink-0 text-xs font-bold">
                        {idx + 1}
                      </span>
                      <span>{point}</span>
                    </li>
                  ))}
                </ul>
              </motion.div>

              {/* Featured Image */}
              {post.imageUrl && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 }}
                  className="rounded-2xl overflow-hidden mb-8 shadow-lg"
                >
                  <img 
                    src={post.imageUrl} 
                    alt={post.title}
                    className="w-full h-64 md:h-80 object-cover"
                  />
                </motion.div>
              )}

              {/* Excerpt */}
              {post.excerpt && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.15 }}
                  className="bg-white rounded-xl p-6 mb-8 border-l-4 border-primary shadow-sm"
                >
                  <p className="text-lg text-foreground leading-relaxed font-medium italic">
                    &ldquo;{post.excerpt}&rdquo;
                  </p>
                </motion.div>
              )}

              {/* Article Content */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="bg-white rounded-2xl p-6 md:p-8 shadow-sm border border-border"
              >
                {contentSections.map((section, idx) => (
                  <ContentSection key={idx} section={section} index={idx} />
                ))}

                {/* Expert Note */}
                <div className="mt-8 bg-accent/10 rounded-xl p-6 border border-accent/20">
                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 bg-accent/20 rounded-full flex items-center justify-center flex-shrink-0">
                      <AlertCircle className="w-6 h-6 text-accent" />
                    </div>
                    <div>
                      <h4 className="font-semibold text-foreground mb-2">Expert Note</h4>
                      <p className="text-sm text-muted-foreground">
                        This article is for informational purposes only. Always consult with a qualified orthopedic surgeon 
                        for personalized medical advice. Dr. Harsha offers consultations at Apollo Hospitals, Financial District, Hyderabad.
                      </p>
                    </div>
                  </div>
                </div>
              </motion.div>

              {/* Tags & Share */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="bg-white rounded-2xl p-6 mt-6 shadow-sm border border-border"
              >
                {/* Tags */}
                {post.tags && post.tags.length > 0 && (
                  <div className="flex flex-wrap items-center gap-2 mb-6 pb-6 border-b border-border">
                    <Tag className="w-4 h-4 text-muted-foreground" />
                    <span className="text-sm font-medium text-foreground">Topics:</span>
                    {post.tags.map((tag, index) => (
                      <Link 
                        key={index}
                        to={`/blog?search=${encodeURIComponent(tag)}`}
                        className="text-xs bg-secondary hover:bg-primary hover:text-white text-muted-foreground px-3 py-1.5 rounded-full transition-colors"
                      >
                        {tag}
                      </Link>
                    ))}
                  </div>
                )}

                {/* Share */}
                <div className="flex flex-wrap items-center justify-between gap-4">
                  <span className="text-sm font-medium text-foreground flex items-center gap-2">
                    <Share2 className="w-4 h-4" />
                    Share this article:
                  </span>
                  <div className="flex gap-2">
                    <button 
                      onClick={() => handleShare('facebook')}
                      className="w-10 h-10 flex items-center justify-center rounded-full bg-[#1877F2] text-white hover:scale-110 transition-transform"
                      aria-label="Share on Facebook"
                    >
                      <Facebook className="w-4 h-4" />
                    </button>
                    <button 
                      onClick={() => handleShare('twitter')}
                      className="w-10 h-10 flex items-center justify-center rounded-full bg-[#1DA1F2] text-white hover:scale-110 transition-transform"
                      aria-label="Share on Twitter"
                    >
                      <Twitter className="w-4 h-4" />
                    </button>
                    <button 
                      onClick={() => handleShare('linkedin')}
                      className="w-10 h-10 flex items-center justify-center rounded-full bg-[#0A66C2] text-white hover:scale-110 transition-transform"
                      aria-label="Share on LinkedIn"
                    >
                      <Linkedin className="w-4 h-4" />
                    </button>
                    <button 
                      onClick={() => handleShare('whatsapp')}
                      className="w-10 h-10 flex items-center justify-center rounded-full bg-[#25D366] text-white hover:scale-110 transition-transform"
                      aria-label="Share on WhatsApp"
                    >
                      <MessageCircle className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              </motion.div>

              {/* Author Card */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.35 }}
                className="bg-gradient-to-br from-charcoal to-charcoal/90 rounded-2xl p-6 mt-6 text-white"
              >
                <div className="flex flex-col sm:flex-row items-start gap-4">
                  <div className="w-20 h-20 bg-white/10 rounded-full flex items-center justify-center flex-shrink-0">
                    <User className="w-10 h-10 text-white/80" />
                  </div>
                  <div className="flex-1">
                    <p className="text-white/60 text-sm mb-1">Written by</p>
                    <h4 className="font-semibold text-xl mb-1">{post.author || 'Dr. B Harsha Vardhana Reddy'}</h4>
                    <p className="text-primary font-medium text-sm mb-3">Senior Consultant Orthopedic Surgeon</p>
                    <p className="text-white/70 text-sm mb-4">
                      DNB Orthopedics | Fellowship in Joint Replacement & Arthroscopy | 15+ Years Experience | 4,000+ Surgeries
                    </p>
                    <Link to="/about">
                      <Button size="sm" variant="outline" className="border-white/30 text-white hover:bg-white/10">
                        View Full Profile
                      </Button>
                    </Link>
                  </div>
                </div>
              </motion.div>
            </div>

            {/* Sidebar */}
            <div className="lg:col-span-4">
              <div className="sticky top-24 space-y-6">
                {/* Table of Contents */}
                {tableOfContents.length > 0 && (
                  <motion.div
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.2 }}
                    className="bg-white rounded-2xl p-5 border border-border shadow-sm"
                  >
                    <h3 className="font-semibold text-foreground mb-4 flex items-center gap-2">
                      <BookOpen className="w-4 h-4 text-primary" />
                      In This Article
                    </h3>
                    <nav className="space-y-2">
                      {tableOfContents.slice(0, 6).map((item, idx) => (
                        <a
                          key={idx}
                          href={`#section-${idx}`}
                          className={`block text-sm py-1.5 px-3 rounded-lg transition-colors ${
                            item.type === 'h3' ? 'pl-6 text-muted-foreground hover:text-primary' : 'text-foreground hover:bg-secondary font-medium'
                          }`}
                        >
                          {item.title}
                        </a>
                      ))}
                    </nav>
                  </motion.div>
                )}

                {/* CTA Card */}
                <motion.div
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.3 }}
                  className="bg-gradient-to-br from-primary to-primary/90 rounded-2xl p-6 text-white"
                >
                  <h3 className="text-xl font-serif font-semibold mb-3">
                    Need Expert Advice?
                  </h3>
                  <p className="text-white/80 text-sm mb-6">
                    Get personalized treatment recommendations from Dr. Harsha Reddy.
                  </p>
                  <Link to="/contact">
                    <Button className="w-full bg-accent hover:brightness-110 text-accent-foreground mb-3">
                      Book Consultation
                    </Button>
                  </Link>
                  <a href="tel:+919959964567" className="block">
                    <Button variant="outline" className="w-full border-white text-white hover:bg-white/10">
                      <Phone className="w-4 h-4 mr-2" />
                      +91 99599 64567
                    </Button>
                  </a>
                </motion.div>

                {/* Related Posts */}
                {relatedPosts.length > 0 && (
                  <motion.div
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.4 }}
                    className="bg-white rounded-2xl p-5 border border-border shadow-sm"
                  >
                    <h3 className="font-semibold text-foreground mb-4">Related Articles</h3>
                    <div className="space-y-4">
                      {relatedPosts.map((relPost, idx) => (
                        <Link 
                          key={idx}
                          to={`/blog/${relPost.slug}`}
                          className="group flex gap-3"
                        >
                          <div className="w-16 h-16 rounded-lg overflow-hidden flex-shrink-0 bg-secondary">
                            <img 
                              src={relPost.imageUrl || `https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=100&q=80&sig=${idx}`}
                              alt={relPost.title}
                              className="w-full h-full object-cover group-hover:scale-110 transition-transform"
                            />
                          </div>
                          <div className="flex-1 min-w-0">
                            <h4 className="text-sm font-medium text-foreground group-hover:text-primary transition-colors line-clamp-2">
                              {relPost.title}
                            </h4>
                            <p className="text-xs text-muted-foreground mt-1">
                              {relPost.readTime || '5 min read'}
                            </p>
                          </div>
                        </Link>
                      ))}
                    </div>
                  </motion.div>
                )}

                {/* Quick Topics */}
                <motion.div
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.5 }}
                  className="bg-secondary/50 rounded-2xl p-5"
                >
                  <h3 className="font-semibold text-foreground mb-3">Popular Topics</h3>
                  <div className="flex flex-wrap gap-2">
                    {['Knee Replacement', 'Hip Surgery', 'ACL Injury', 'Shoulder Pain', 'Sports Medicine'].map((topic) => (
                      <Link 
                        key={topic}
                        to={`/blog?search=${encodeURIComponent(topic)}`}
                        className="text-xs bg-white px-3 py-1.5 rounded-full text-muted-foreground hover:text-primary hover:shadow-sm transition-all"
                      >
                        {topic}
                      </Link>
                    ))}
                  </div>
                </motion.div>
              </div>
            </div>
          </div>

          {/* Back to Blog */}
          <div className="mt-12 text-center">
            <Link to="/blog" className="inline-flex items-center gap-2 text-primary hover:underline font-medium">
              <ArrowLeft className="w-4 h-4" />
              Back to All Articles
            </Link>
          </div>
        </div>
      </article>
    </Layout>
  );
};

export default BlogPost;
