import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import Layout from '@/components/layout/Layout';
import SEO from '@/components/SEO';
import Breadcrumbs from '@/components/Breadcrumbs';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { 
  Calendar,
  Clock,
  User,
  ArrowLeft,
  ArrowRight,
  Phone,
  Share2,
  Tag,
  Loader2,
  BookOpen,
  CheckCircle,
  MessageCircle,
  Facebook,
  Twitter,
  Linkedin
} from 'lucide-react';
import { seoBlogPosts } from '@/data/seoBlogPosts';
import { autoGeneratedBlogs } from '@/data/autoGeneratedBlogs';
import newBlogPosts from '@/data/newBlogPosts';
import staticBlogPosts from '@/data/blogPosts';

// Combine all blog sources
const allBlogPosts = [...autoGeneratedBlogs, ...seoBlogPosts, ...newBlogPosts, ...staticBlogPosts];

const API_URL = process.env.REACT_APP_BACKEND_URL || '';

// Transform CMS blog data to match static data format
const transformCmsBlog = (cmsData) => {
  if (!cmsData || !cmsData.content) return null;
  const content = cmsData.content;
  
  return {
    id: cmsData.slug,
    slug: cmsData.slug,
    title: cmsData.title,
    metaTitle: cmsData.meta_title,
    metaDescription: cmsData.meta_description,
    keywords: cmsData.keywords?.join(', '),
    author: content.author || 'Dr. B Harsha Vardhana Reddy',
    publishedDate: cmsData.published_at || cmsData.created_at,
    category: content.category || 'Orthopedics',
    readTime: content.readTime || '5 min',
    imageUrl: content.imageUrl,
    excerpt: content.excerpt,
    content: content.body || content.content,
    tags: cmsData.keywords || [],
    keyTakeaways: content.keyTakeaways || [],
    tableOfContents: content.tableOfContents || []
  };
};

const BlogPost = () => {
  const { slug } = useParams();
  const [post, setPost] = useState(null);
  const [loading, setLoading] = useState(true);
  const [relatedPosts, setRelatedPosts] = useState([]);

  useEffect(() => {
    const fetchBlog = async () => {
      setLoading(true);
      let foundPost = null;
      
      try {
        // Try to fetch from CMS first
        const response = await fetch(`${API_URL}/api/cms/blogs/${slug}`);
        if (response.ok) {
          const cmsData = await response.json();
          foundPost = transformCmsBlog(cmsData);
        }
      } catch (err) {
        console.warn('CMS fetch failed, using static data:', err.message);
      }
      
      // Fallback to static data
      if (!foundPost) {
        foundPost = allBlogPosts.find(p => p.slug === slug);
      }
      
      setPost(foundPost);
      
      // Get related posts based on tags
      if (foundPost) {
        const postTags = foundPost.tags || [];
        const related = allBlogPosts
          .filter(p => p.slug !== slug)
          .filter(p => (p.tags || []).some(tag => postTags.includes(tag)))
          .slice(0, 3);
        setRelatedPosts(related);
      }
      
      setLoading(false);
    };

    fetchBlog();
    window.scrollTo(0, 0);
  }, [slug]);

  const handleShare = (platform) => {
    const url = window.location.href;
    const title = post?.title || '';
    
    const shareUrls = {
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,
      twitter: `https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(title)}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`,
      whatsapp: `https://wa.me/?text=${encodeURIComponent(title + ' ' + url)}`
    };
    
    window.open(shareUrls[platform], '_blank', 'width=600,height=400');
  };

  if (loading) {
    return (
      <Layout>
        <div className="min-h-screen flex items-center justify-center">
          <Loader2 className="w-10 h-10 animate-spin text-primary" />
          <span className="ml-4 text-lg text-muted-foreground">Loading article...</span>
        </div>
      </Layout>
    );
  }
  
  if (!post) {
    return (
      <Layout>
        <div className="min-h-screen flex flex-col items-center justify-center py-20">
          <BookOpen className="w-20 h-20 text-muted-foreground/30 mb-6" />
          <h1 className="text-2xl font-bold mb-4">Article Not Found</h1>
          <p className="text-muted-foreground mb-6">The article you're looking for doesn't exist or has been moved.</p>
          <Link to="/blog">
            <Button className="gap-2">
              <ArrowLeft className="w-4 h-4" />
              Back to Blog
            </Button>
          </Link>
        </div>
      </Layout>
    );
  }

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-IN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  // Generate key takeaways from content if not provided
  const keyTakeaways = post.keyTakeaways?.length > 0 ? post.keyTakeaways : [
    `Comprehensive guide to ${post.title?.toLowerCase().replace('2025', '').trim()}`,
    'Evidence-based treatment approaches and techniques',
    'Recovery timelines and realistic expectations',
    'Cost information and insurance coverage in Hyderabad',
    'Expert recommendations from 15+ years of experience'
  ];

  // Article Schema for SEO
  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "MedicalWebPage",
    "headline": post.title,
    "author": {
      "@type": "Person",
      "name": post.author || "Dr. B Harsha Vardhana Reddy",
      "jobTitle": "Senior Consultant Orthopedic Surgeon",
      "affiliation": {
        "@type": "Hospital",
        "name": "Yashoda Hospital, Hyderabad"
      }
    },
    "datePublished": post.publishedDate || post.published_date,
    "image": post.imageUrl,
    "publisher": {
      "@type": "Organization",
      "name": "Dr. B Harsha Vardhana Reddy",
      "logo": "https://drharshaortho.com/images/dr-harsha-logo.png"
    },
    "medicalAudience": "Patient"
  };

  return (
    <Layout>
      <SEO 
        title={post.metaTitle || `${post.title} | Dr. Harsha Reddy`}
        description={post.metaDescription || post.excerpt}
        keywords={post.keywords}
      />
      
      <script type="application/ld+json">
        {JSON.stringify(articleSchema)}
      </script>

      {/* Breadcrumb */}
      <div className="bg-secondary border-b border-border">
        <div className="container-medical py-3">
          <Breadcrumbs 
            items={[
              { name: 'Blog', path: '/blog' },
              { name: post.title, path: `/blog/${slug}` }
            ]}
          />
        </div>
      </div>

      {/* Hero Section */}
      <section className="relative">
        <div className="absolute inset-0 h-[350px] md:h-[450px]">
          <img 
            src={post.imageUrl || 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=1200&q=80'}
            alt={post.title}
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-charcoal via-charcoal/80 to-charcoal/40" />
        </div>
        
        <div className="relative container-medical pt-16 pb-28 md:pt-24 md:pb-36">
          <div className="max-w-4xl">
            {/* Category & Read Time */}
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="flex flex-wrap gap-3 mb-6"
            >
              <span className="inline-flex items-center gap-1 px-4 py-1.5 bg-primary text-white text-sm font-medium rounded-full">
                <Tag className="w-3 h-3" />
                {post.category || post.tags?.[0] || 'Orthopedics'}
              </span>
              <span className="inline-flex items-center gap-1 px-4 py-1.5 bg-white/20 text-white text-sm rounded-full">
                <Clock className="w-3 h-3" />
                {post.readTime || '5 min read'}
              </span>
            </motion.div>
            
            {/* Title */}
            <motion.h1 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-2xl md:text-3xl lg:text-4xl xl:text-5xl font-serif font-semibold text-white mb-6 leading-tight"
            >
              {post.title}
            </motion.h1>
            
            {/* Meta Info */}
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="flex flex-wrap items-center gap-6 text-white/80"
            >
              <div className="flex items-center gap-2">
                <div className="w-10 h-10 bg-primary rounded-full flex items-center justify-center">
                  <User className="w-5 h-5 text-white" />
                </div>
                <div>
                  <p className="text-sm font-medium text-white">{post.author || 'Dr. B Harsha Vardhana Reddy'}</p>
                  <p className="text-xs text-white/60">Orthopedic Surgeon</p>
                </div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <Calendar className="w-4 h-4" />
                {formatDate(post.publishedDate || post.published_date)}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Article Content */}
      <article className="relative -mt-16 pb-16">
        <div className="container-medical">
          <div className="grid lg:grid-cols-12 gap-8">
            {/* Main Content */}
            <div className="lg:col-span-8">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="bg-card rounded-2xl shadow-xl p-6 md:p-10"
              >
                {/* Key Takeaways */}
                <div className="bg-gradient-to-br from-primary/5 to-accent/5 rounded-xl p-6 mb-8 border border-primary/10">
                  <h2 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-primary" />
                    Key Takeaways
                  </h2>
                  <ul className="space-y-3">
                    {keyTakeaways.map((point, idx) => (
                      <li key={idx} className="flex items-start gap-3 text-sm text-muted-foreground">
                        <span className="w-6 h-6 bg-primary/10 text-primary rounded-full flex items-center justify-center flex-shrink-0 text-xs font-medium">
                          {idx + 1}
                        </span>
                        {point}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Excerpt */}
                {post.excerpt && (
                  <p className="text-lg text-muted-foreground leading-relaxed mb-8 font-medium border-l-4 border-primary pl-4">
                    {post.excerpt}
                  </p>
                )}

                {/* Article Body */}
                <div 
                  className="prose prose-lg max-w-none
                    prose-headings:font-serif prose-headings:text-foreground
                    prose-h2:text-2xl prose-h2:mt-10 prose-h2:mb-4 prose-h2:pb-2 prose-h2:border-b prose-h2:border-border
                    prose-h3:text-xl prose-h3:mt-8 prose-h3:mb-4
                    prose-h4:text-lg prose-h4:mt-6 prose-h4:mb-3
                    prose-p:text-muted-foreground prose-p:leading-relaxed prose-p:mb-4
                    prose-li:text-muted-foreground prose-li:mb-2
                    prose-strong:text-foreground prose-strong:font-semibold
                    prose-a:text-primary prose-a:no-underline hover:prose-a:underline
                    prose-ul:my-4 prose-ol:my-4
                    prose-table:border-collapse prose-table:w-full prose-table:my-6
                    prose-th:bg-secondary prose-th:p-3 prose-th:text-left prose-th:border prose-th:border-border prose-th:font-semibold
                    prose-td:p-3 prose-td:border prose-td:border-border
                    prose-blockquote:border-l-4 prose-blockquote:border-primary prose-blockquote:bg-secondary/50 prose-blockquote:py-2 prose-blockquote:px-4 prose-blockquote:rounded-r-lg prose-blockquote:not-italic"
                  dangerouslySetInnerHTML={{ 
                    __html: (post.content || '')
                      .replace(/\n\n/g, '</p><p>')
                      .replace(/\n/g, '<br/>')
                      .replace(/## (.*?)(?=\n|$)/g, '</p><h2>$1</h2><p>')
                      .replace(/### (.*?)(?=\n|$)/g, '</p><h3>$1</h3><p>')
                      .replace(/#### (.*?)(?=\n|$)/g, '</p><h4>$1</h4><p>')
                      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                      .replace(/\*(.*?)\*/g, '<em>$1</em>')
                      .replace(/- (.*?)(?=\n|$)/g, '<li>$1</li>')
                      .replace(/(<li>.*<\/li>)+/g, '<ul>$&</ul>')
                  }}
                />

                {/* Tags */}
                {post.tags && post.tags.length > 0 && (
                  <div className="mt-10 pt-6 border-t border-border">
                    <div className="flex flex-wrap items-center gap-2">
                      <Tag className="w-4 h-4 text-muted-foreground" />
                      <span className="text-sm font-medium text-foreground mr-2">Topics:</span>
                      {post.tags.map((tag, index) => (
                        <span 
                          key={index}
                          className="text-xs bg-secondary hover:bg-secondary/80 text-muted-foreground px-3 py-1.5 rounded-full cursor-pointer transition-colors"
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                {/* Share */}
                <div className="mt-8 pt-6 border-t border-border">
                  <div className="flex flex-wrap items-center gap-4">
                    <span className="text-sm font-medium text-foreground flex items-center gap-2">
                      <Share2 className="w-4 h-4" />
                      Share this article:
                    </span>
                    <div className="flex gap-2">
                      <button 
                        onClick={() => handleShare('facebook')}
                        className="w-9 h-9 flex items-center justify-center rounded-full bg-[#1877F2] text-white hover:opacity-90 transition-opacity"
                      >
                        <Facebook className="w-4 h-4" />
                      </button>
                      <button 
                        onClick={() => handleShare('twitter')}
                        className="w-9 h-9 flex items-center justify-center rounded-full bg-[#1DA1F2] text-white hover:opacity-90 transition-opacity"
                      >
                        <Twitter className="w-4 h-4" />
                      </button>
                      <button 
                        onClick={() => handleShare('linkedin')}
                        className="w-9 h-9 flex items-center justify-center rounded-full bg-[#0A66C2] text-white hover:opacity-90 transition-opacity"
                      >
                        <Linkedin className="w-4 h-4" />
                      </button>
                      <button 
                        onClick={() => handleShare('whatsapp')}
                        className="w-9 h-9 flex items-center justify-center rounded-full bg-[#25D366] text-white hover:opacity-90 transition-opacity"
                      >
                        <MessageCircle className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>

                {/* Author Box */}
                <div className="mt-10 p-6 bg-secondary rounded-xl">
                  <div className="flex flex-col sm:flex-row items-start gap-4">
                    <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center flex-shrink-0">
                      <User className="w-10 h-10 text-primary" />
                    </div>
                    <div className="flex-1">
                      <h4 className="font-semibold text-lg text-foreground">{post.author || 'Dr. B Harsha Vardhana Reddy'}</h4>
                      <p className="text-sm text-primary font-medium mb-2">
                        Senior Consultant Orthopedic Surgeon
                      </p>
                      <p className="text-sm text-muted-foreground mb-3">
                        DNB Orthopedics | Fellowship in Joint Replacement | Fellowship in Arthroscopy | 15+ Years Experience | 4,000+ Successful Surgeries
                      </p>
                      <p className="text-sm text-muted-foreground">
                        Associate Consultant at Yashoda Hospital, Hitec City, Hyderabad. Founder of AgileOrtho Healthcare.
                      </p>
                    </div>
                  </div>
                </div>
              </motion.div>
            </div>

            {/* Sidebar */}
            <div className="lg:col-span-4">
              <div className="sticky top-24 space-y-6">
                {/* CTA Card */}
                <motion.div
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.4 }}
                  className="bg-gradient-to-br from-primary to-primary/90 rounded-2xl p-6 text-white"
                >
                  <h3 className="text-xl font-serif font-semibold mb-3">
                    Need Expert Advice?
                  </h3>
                  <p className="text-white/80 text-sm mb-6">
                    Schedule a consultation with Dr. Harsha for personalized treatment options.
                  </p>
                  <Link to="/contact">
                    <Button className="w-full bg-accent hover:brightness-110 text-accent-foreground mb-3">
                      Book Consultation
                    </Button>
                  </Link>
                  <a href="tel:+919959964567" className="block">
                    <Button variant="outline" className="w-full border-white text-white hover:bg-white/10">
                      <Phone className="w-4 h-4 mr-2" />
                      Call +91 99599 64567
                    </Button>
                  </a>
                </motion.div>

                {/* Related Posts */}
                {relatedPosts.length > 0 && (
                  <motion.div
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.5 }}
                    className="bg-card rounded-2xl p-6 border border-border"
                  >
                    <h3 className="font-semibold text-foreground mb-4 flex items-center gap-2">
                      <BookOpen className="w-4 h-4 text-primary" />
                      Related Articles
                    </h3>
                    <div className="space-y-4">
                      {relatedPosts.map((relPost, idx) => (
                        <Link 
                          key={idx}
                          to={`/blog/${relPost.slug}`}
                          className="group block"
                        >
                          <article className="flex gap-3">
                            <div className="w-16 h-16 rounded-lg overflow-hidden flex-shrink-0">
                              <img 
                                src={relPost.imageUrl || `https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=100&q=80&sig=${idx}`}
                                alt={relPost.title}
                                className="w-full h-full object-cover group-hover:scale-110 transition-transform"
                              />
                            </div>
                            <div className="flex-1 min-w-0">
                              <h4 className="text-sm font-medium text-foreground group-hover:text-primary transition-colors line-clamp-2">
                                {relPost.title}
                              </h4>
                              <p className="text-xs text-muted-foreground mt-1">
                                {relPost.readTime || '5 min read'}
                              </p>
                            </div>
                          </article>
                        </Link>
                      ))}
                    </div>
                  </motion.div>
                )}

                {/* Quick Links */}
                <motion.div
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.6 }}
                  className="bg-secondary rounded-2xl p-6"
                >
                  <h3 className="font-semibold text-foreground mb-4">Popular Topics</h3>
                  <div className="flex flex-wrap gap-2">
                    {['Knee Replacement', 'Hip Surgery', 'ACL Injury', 'Shoulder Pain', 'Sports Medicine', 'Arthritis'].map((topic) => (
                      <Link 
                        key={topic}
                        to={`/blog?search=${encodeURIComponent(topic)}`}
                        className="text-xs bg-white px-3 py-1.5 rounded-full text-muted-foreground hover:text-primary hover:bg-primary/5 transition-colors"
                      >
                        {topic}
                      </Link>
                    ))}
                  </div>
                </motion.div>
              </div>
            </div>
          </div>

          {/* Back to Blog */}
          <div className="mt-12 text-center">
            <Link to="/blog" className="inline-flex items-center gap-2 text-primary hover:underline font-medium">
              <ArrowLeft className="w-4 h-4" />
              Back to All Articles
            </Link>
          </div>
        </div>
      </article>
    </Layout>
  );
};

export default BlogPost;
